apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }} #teste-mateus-v3
  namespace: mateus-santos-v3
spec:
  selector:
     app: mateus
  ports:
  - port: 80
    targetPort: 80




apiVersion: v1
kind: Service
metadata:
  name: {{ include "mateushelm.fullname" . }}
  labels:
    {{- include "mateushelm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mateushelm.selectorLabels" . | nindent 4 }}
